name: push-to-master
run-name: Building branch from push to master
on:
  push:
    branches:
      - master
jobs:
  build-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Build with Next.js
        run: yarn
          yarn build
